### ISSUE TITLE
📋 Create a Project Backlog

### ISSUE THREAD

**Issue by gitaclue1** [chingu-voyages/v28-bears-team-10#3]
**__Task Description__**
- [ ] Watch the [How to Create a Project Backlog](https://youtu.be/FaoT-DTtXyA) video
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/FaoT-DTtXyA)
- [ ] Identify & prioritize features
- [ ] Create an epic for each feature
- [ ] Choose the highest priority epics & divide them into user stories
- [ ] Add your epics & user stories to a backlog tool. Due to it’s tight integration with GitHub we suggest using ZenHub (it’s free for teams using public repositories)
- [ ] Prioritize the user stories

**__Technical Considerations__**
N/a

**__Additional Considerations__**
During the Voyage you’ll refine the Project Backlog and in every Sprint you’ll move tasks from it to the Sprint Backlog. This is part of the Agile process helps you and your team concentrate only on the tasks that must be completed in that Sprint.
