### ISSUE TITLE
📤 Define & prioritize MVP features

### ISSUE THREAD

**Issue by gitaclue1** [chingu-voyages/v28-bears-team-10#4]
**__Task Description__**
- [ ] Each team member should add their ideas to the [Project Vision & Feature Planning template](https://docs.google.com/document/d/1pG-6ihL47P6IpMtcgVeb5_DWoatZcsMTwx_lGDmfh9o/edit?usp=sharing) before the team meeting
- [ ] Prioritize each feature - _Must Have_, _Should Have_, _Nice to Have_
- [ ] Meet with the team to review each feature & refine priorities

**__Technical Considerations__**
N/a

**__Additional Considerations__**
All _Must Have_ tasks will make up your MVP. Make sure that you control the scope of the project by limiting the number of _Must Have_ features to the ones you can reasonably complete by the end of Sprint 6.

Remember that you can always add new features once you complete the MVP.
