### ISSUE TITLE
🧑‍🤝‍🧑 Conduct Kickoff meeting

### ISSUE THREAD

**Issue by gitaclue1** [chingu-voyages/v28-bears-team-10#6]
**__Task Description__**
- [ ] Using everyone's availability posted to When2Meet schedule a Kickoff meeting
- [ ] Use the [Kickoff meeting template](https://docs.google.com/document/d/1ozP5lLj_R0kqCWdXEpFDR6sIlP9miXp74DFKZlJyktE/edit?usp=sharing) in the shared document directory we've provided to guide the discussion and to record notes, decisions, and assignments
- [ ] Set a time for your next meeting for later in the week

**__Technical Considerations__**
N/a

**__Additional Considerations__**
N/a
